var lanenglish = [["John ate an apple before afternoon<br>","before afternoon John ate an apple<br>", "John before afternoon ate an apple<br>"], ["some students like to study in the night<br>", "at night some students like to study<br>"],["John and Mary went to church<br>","Mary and John went to church<br>"],["John went to church after eating<br>","after eating John went to church<br>","John after eating went to church<br>"],["did he go to market<br>","he did go to market<br>"],["the woman who called my sister sells cosmetics<br>","the woman who sells cosmetics called my sister<br>","my sister who sells cosmetics called the woman<br>","my sister who called the woman sells cosmetics<br>"],["John goes to the library and studies<br>","John studies and goes to the library<br>"],["John ate an apple so did she<br>","she ate an apple so did John<br>"],["the teacher returned the book after she noticed the error","the teacher noticed the error after she returned the book<br>","after the teacher returned the book she noticed the error<br>","after the teacher noticed the error she returned the book<br>","she returned the book after the teacher noticed the error<br>","she noticed the error after the teacher returned the book<br>","after she returned the book the teacher noticed the error<br>","after she noticed the error the teacher returned the book<br>"],["I told her that I bought a book yesterday<br>","I told her yesterday that I bought a book
<br>","yesterday I told her that I bought a book<br>","I bought a book that I told her yesterday<br>","I bought a book yesterday that I told her<br>","yesterday I bought a book that I told her<br>"]
];

var langhindi=[["राम और श्याम बाजार गयें<br>","राम और श्याम गयें बाजार<br>","बाजार गयें राम और श्याम<br>","गयें बाजार राम और श्याम<br>"],["राम सोया और श्याम भी<br>",
"श्याम सोया और राम भी<br>","सोया श्याम और राम भी<br>","सोया राम और श्याम भी<br>"],["मैंने उसे बताया कि राम सो रहा है<br>","मैंने उसे बताया कि सो रहा है राम<br>","उसे मैंने बताया कि राम सो रहा है<br>","उसे मैंने बताया कि सो रहा है राम<br>","मैंने बताया उसे कि राम सो रहा है<br>,"मैंने बताया उसे कि सो रहा है राम<br>","उसे बताया मैंने कि राम सो रहा है<br>","उसे बताया मैंने कि सो रहा है राम<br>","बताया मैंने उसे कि राम सो रहा है<br>","बताया मैंने उसे कि सो रहा है राम<br>","बताया उसे मैंने कि राम सो रहा है<br>","बताया उसे मैंने कि सो रहा है राम<br>"],["राम खाकर सोया<br>","खाकर राम सोया<br>","राम सोया खाकर<br>","खाकर सोया राम<br>","सोया राम खाकर<br>","सोया खाकर राम<br>"],["बिल्लियों को मारकर कुत्ता सो गया<br>","मारकर बिल्लियों को कुत्ता सो गया<br>","बिल्लियों को मारकर सो गया कुत्ता<br>","मारकर बिल्लियों को सो गया कुत्ता<br>","कुत्ता सो गया बिल्लियों को मारकर<br>","कुत्ता सो गया मारकर बिल्लियों को<br>","सो गया कुत्ता बिल्लियों को मारकर<br>","सो गया कुत्ता मारकर बिल्लियों को<br>"],["एक लाल किताब वहाँ है<br>","एक लाल किताब है वहाँ<br>","वहाँ है एक लाल किताब<br>","है वहाँ एक लाल किताब<br>"],["एक बड़ी सी किताब वहाँ है<br>","एक बड़ी सी किताब है वहाँ<br>","बड़ी सी एक किताब वहाँ है<br>","बड़ी सी एक किताब है वहाँ<br>","वहाँ है एक बड़ी सी किताब<br>","वहाँ है बड़ी सी एक किताब<br>","है वहाँ एक बड़ी सी किताब<br>","है वहाँ बड़ी सी एक किताब<br>"]
];







                             